### ISSUE TITLE
교수님 명언집

### ISSUE THREAD

**Issue by jeuxdeau** [jeuxdeau/Vaseline#13]
수업을 열심히 듣고 그날 들은 감동적인 말씀을 기록하는 공간입니다 -팬클럽 회장-

**Comment by jeuxdeau** [comment]
1. 여러분 페이스북에 글 올릴 때 쿨하게 보이려고 하잖아요. 코딩할 때도 마찬가지로 내 코드가 얼마나 쿨해 보일지를 생각해야 돼요.

2. 교수님: 최신... 최신이 영어로 뭐지...
용현조교님: ...컨템포러리?
교수님: 그건 니 생각이고 그게 아냐

3. (수업 자료로 쓰는 곤교수님) ppt에 있는 말 무슨 말인지 모르겠네요... 쓰는 사람은 이해가 돼서 썼겠지만 저는 읽는 사람 입장으로.. 이렇게 쓰면 이해가 안 되잖아요?

4. 토니 호는... 너무 늙었어요
얼마 전에 제 발표도 보고. 얘기도 했는데
토니 호는... 너무 늙었어요
너무.... 늙었어요

5. 토니 호랑 로빈 밀너랑 똑같이 생겼어요. 저는 똑같이 생긴 사람이 모자 쓰고 벗고 하는 줄 알았거든요 어떤 날은 모자 쓰고 오고 어떤 날은 벗고 오고 근데 어느날 같은 사람 둘이 하나는 모자를 쓰고 하나는 벗고 온 거에요. 그때 알았어요 (둘은 다른 사람이라는 걸)

6. (디자인 패턴 SOLID에 대해 이야기하며)
여러분 솔리드 아세요?
이 밤의 끝을 잡고

7. 무어의 법칙 같네요 학생들이 수업을 한 번 하면 반으로 줄고 실습을 하면 또 반으로 줄고

8. (열 명 남짓 출석하자) 우리 수업은 교양수업이니까 상처받지 않아요

9. 제 학부 학점은 4.15정도 되는데. 4.3 만점에.

10. 여러분 출석에 대해 어떻게 생각해요? 저도 학부때. 출석 안해도 A+ 받을 수 있는 거 예를 들면 **미적분학** 같은. 그런 건 출석 안 했는데 (5월 8일)

11. (수업 중인데 [가난과 질병의 상관 관계를 밝혀낸 전미 소아과 협회장]의 아들이 계속 교수님한테 메시지를 보냄)
교수님: 음.. 나 수업 중인데. I'm teaching
(또 메시지 옴)
교수님: 아임 티칭이 나 수업 중이라는 게 아닌가???
현석: I'm on class 라고 해보세요
교수님: (그대로 받아 적으며) 아..임.. 온... 클래스...

12. 아이 뭐야! 완전 거꾸로 말했네! (실제로는 똑바로 말씀하신 거였음...)

**Comment by jeuxdeau** [comment]
![image](https://user-images.githubusercontent.com/22112344/39959442-9ec33748-564c-11e8-9793-7fc2aa7410f8.png)
13. 윤년이면 일년이 364일이죠. 1년은 365일 이상이다. 이게 틀렸네.

14. 이런 관계를 **갈루아 커넥션**이라고 해요
https://en.wikipedia.org/wiki/Galois_connection#Definitions
(뭔가 신기한 설명이었다...
근데 양쪽으로 가는 함수가 다 있 다고 했는데
ab->ab abba->ab bbbbbbbba->ab 이건 무슨 함수인지 알겠는데
그럼 반대로 ab->? 이 함수는 어떻게 정의
늘 자기 자신으로?)

**Comment by jeuxdeau** [comment]
15. 페어 프로그래밍, 웬만하면 남학생 여학생이 나란히 앉아서 하면 좋겠죠.

16. (학생들도 몇 명 없고 조교도 아무도 안 온 날) 조교들도 수업을 안 와도 된다고 생각하나봐요.

17. 나는 문제를 풀 때 한 가지 해결 방법에만 매달리지 않는다. 가능한 모든 경우의 수를 생각한 다음에, 여러 가지를 시도해 보고, 아니다 싶은 건 빨리 걸러내야 한다. 그걸 계속 하면 답이 나온다. 한 가지 방법에 매달려서는 절대 답이 나올 수가 없다. @minkiminki

**Comment by minkiminki** [comment]
18. 이순신이 그랬죠. 나의 죽음을 적에게 알리지 말라고. 그거처럼 클래스 속구현을 알리면 안 돼요.

**Comment by petrosyh** [comment]
안녕하세요.

"토니 호"라고 하는 것 보다 "Tony Hoare"나 "토니 호어"라고 하는 것이 좋을 것 같습니다.

https://ko.wikipedia.org/wiki/%EC%B0%B0%EC%8A%A4_%EC%95%A4%ED%84%B0%EB%8B%88_%EB%A6%AC%EC%B2%98%EB%93%9C_%ED%98%B8%EC%96%B4
https://en.wikipedia.org/wiki/Tony_Hoare

**Comment by jeuxdeau** [comment]
@petrosyh 
조교님
^-^

**Comment by jeuxdeau** [comment]
![image](https://user-images.githubusercontent.com/22112344/41089498-e6cd578c-6a7c-11e8-9b60-52868afb7cda.png)
지금까지 명언집을 사랑해 주셔서 감사합니다

**Comment by minkiminki** [comment]
내가 디시인사이드랑 점유율 맞먹었던 노트북인사이드란 사이트를 했었는데
(학생들 의심스러운 눈빛)
모르겠으면 나무위키에 쳐봐

**Comment by petrosyh** [comment]
@minkiminki 
web.archive.org/web/20001122013700/http://www.notebookinside.com/
감동실화

**Comment by jeuxdeau** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋ
여기가 sf 대나무숲틴가요 ㅋㅋ

**Comment by jeuxdeau** [comment]
@petrosyh 조교님 미국 재미써여? @minkiminki 가 미국에서 공부 안한다고 뒷담화함 ㅡㅡ

**Comment by petrosyh** [comment]
헐 숙제도 열심히하고 공부 개열심히했는데....
@minkiminki

**Comment by jeuxdeau** [comment]
@petrosyh 공부 열시미 하시고 맛있는거 사오셔요
ㅎㅎ

**Comment by alxest** [comment]
0. "Let there be type," and there was type.

**Comment by minkiminki** [comment]
currying은 커리를 만드는게 아니에요~

**Comment by minkiminki** [comment]
수업이 이해가 안 되면 수업을 못한 거에요.
논문이 안 읽히면 논문을 못 쓴 거고요.
