### ISSUE TITLE
Sign Up Page

### ISSUE THREAD

**Issue by jeuxdeau** [jeuxdeau/Vaseline#14]
작성 중인데 이야기해봐야 할 것들이 많아서 올립니다.
자유롭게 의견 남겨주세요. :wink:
- 유저의 나이는 10대/20대/...처럼 받기로 했는데요, 컴패니언의 나이는 어떻게 받을까요?
생일(datetime)로 받나요, 아니면 몇 살인지를 직접 입력할 수 있게 할까요?
- 가입할 때 id만 받는데, 유저를 식별할 수 있는 username을 따로 만들어줘야 할까요?
ex) id는 jeuxdeau 표시되는 이름 username은 박우빈...
- 유저 모델에서 연락처 필드는 이메일밖에 없는 것 같은데요. 더 안 필요한가요? 상호 프로포즈가 성공하면 서로의 이메일을 교환하는 건가요?
- 주소를 우편번호 + 상세주소로 받는데 이것을 가지고 어떻게 근거리 유저를 찾아줄 수 있는지...는 제가 조금 더 찾아볼게요. 아니면 위치 정보 받는 것도 좋은 생각일 것 같아요.

**Comment by jinwoo71** [comment]
- 내 기억대로라면 저번에는 생일로 받기로 한듯? 생일로 받는 게 시간 지나고 나이 표시할 때 더 편할 것 같아. 나이로 받으면 언제 +1 씩 해줘야할지도 애매하고.. (매년 1월 1일마다?)  
- 음.. 있으면 확실히 좋을 것 같아. User에게 Nickname이라는 field를 만들까?
- 상호 프로포즈가 성공하면 메시지를 통해서 고객들이 자유롭게 연락처를 교환하는 게 좋을 것 같아. 바로 연락처 공개되면 불편할 고객들도 있을 것 같고.. 메세지를 통해 상대방과 대화를 해본 다음에 이 사람의 강아지와 교배해도 되겠다! 라고 결정하면 그 때 연락처를 교환하는 게 바람직할 듯.
- 위치 정보 받는 거 좋을 것 같아. 이건 찾아보다가 힘들면 다시 말해줘 그러면 나도 자세히 알아볼게!

**Comment by jinwoo71** [comment]
@jeuxdeau 
Signup은 어느정도 되어가? 백엔드에서 아직 signup post부분을 구현못해서 ..

**Comment by jeuxdeau** [comment]
다들 답변 고맙고 진행 상황은 주말 중에 푸시할게요
1. 생일: 걱정되는 부분이 있는데 강아지 생일을 정확히 아는 경우가 드물지 않나요? 특히 유기견들은 정확한 나이도 모르고 추정할 수밖에 없다고 들어서요
2. 유저네임 만들기 ㅇㅋ
3. 이메일만 공개 ㅇㅋ
4. 위치정보 @SonSang 사용 시점일 수도 있고 가입 시점일 수도 있고?

**Comment by jinwoo71** [comment]
@jeuxdeau 
sign up 백엔드 방금 구현 다했어 정리해서 올릴게!
1. 그런 부분은 사용자가 적당히 추정해서 생일 적는게 맞는 것 같아
2. username말고 nickname이라고 해도 될까? backend에서 장고가 제공하는 유저 모델의 id field 이름이 username이라서 그거랑 겹처서 헷갈릴 것 같아 내가 다 정리해서 곧 올릴게

**Comment by jeuxdeau** [comment]
그럼 생일 말고 생년 정도가 나을 거 같은데 어때?

**Comment by jinwoo71** [comment]
음.. 난 괜찮을 것 같아 데이터 다루기 훨씬 쉬울듯!

**Comment by jinwoo71** [comment]
그러면 birth_year 이라는 IntegerField를 만들까요!

**Comment by jeuxdeau** [comment]
내가 짜고 테스트 하면서 드는 생각인데 이 사이트에 가입하기 위해 우편번호 + 주소 + 상세주소까지 입력하는 건 너무 많은 정보를 받아가는 것 같지 않니? 실제로 주소를 사용하는 일도 없고...

**Comment by jinwoo71** [comment]
@jeuxdeau 나도 다 구현해놓고 하는 소리지만 펫퍼처럼 서울시 마포구 이정도의 위치만 받아도 좋을 것 같아..
나중에 떨어진 거리 계산하기 위한 위치도 현재 위치를 받을 거라면 더더욱 쓸모가 없을듯
