### ISSUE TITLE
Signin-frontend 현황 & 새로운 프론트 페이지 추가하는 법에 관해서

### ISSUE THREAD

**Issue by SonSang** [jeuxdeau/Vaseline#16]
![screenshot from 2018-05-12 16-26-59](https://user-images.githubusercontent.com/20263232/39954860-7447e4a0-5601-11e8-8b32-fdc2757bb7c9.png)
로그인 창 : 한 번 로그인 하면 계속 유지됨! 로그아웃 버튼을 만들어야 할 듯.
![screenshot from 2018-05-12 16-27-13](https://user-images.githubusercontent.com/20263232/39954861-7587830c-5601-11e8-8ff7-575c54985b64.png)
메인 페이지 : 일단 등록된 companion들을 모두 데려 올 수 있도록 했어. 

* 새로운 프론트 페이지 추가하는 법 : 

결론부터 : src/index.js에서 새로운 페이지를 바로 추가하지 말고,  PrivateRoute를 새로 추가할 면서 component={new page} 옵션을 주면 됩니다.

설명)

지금 구현된 바로는 url을 입력하면 먼저 src/index.js에서 그 요청을 처리하도록 구현되어 있어.

![screenshot from 2018-05-12 16-39-39](https://user-images.githubusercontent.com/20263232/39954969-9ac8c26e-5603-11e8-8f59-befbec043f25.png)

이 코드에서 중요한 부분이 Route 랑 PrivateRoute 인데, 일단 지금 단계에서 우리 사이트가 제공하는 페이지들은 모두 로그인을 해야 볼 수 있으니까 로그인이 된 상태인지 확인해주는 단계가 필요해. 그 역할을 해주는게 PrivateRoute야! 지금은 List page만 구현되었지만, 예를 들어 detail 페이지가 새로 구현되었고 그 주소가 "/detail"이라고 한다면 저 코드의 Switch 문 내에다가 

`<PrivateRoute path="/detail" component={Detail} />`

만 추가해주면 돼. 그러면 PrivateRoute에서 알아서 지금 사용자가 인증되었는지 확인한 후에, 인증되었으면 Detail 페이지로, 아니면 로그인 페이지로 데려다 줄거야
+) `<PrivateRoute>` 내의 path랑 exact path는 달라! 댓글 참조해줘

**Comment by SonSang** [comment]
![screenshot from 2018-05-13 00-27-20](https://user-images.githubusercontent.com/20263232/39958892-77aead52-5644-11e8-8993-78809f3b7b73.png)
![screenshot from 2018-05-13 00-27-31](https://user-images.githubusercontent.com/20263232/39958894-79076784-5644-11e8-885c-51f8f9893db6.png)
간단한 디자인 추가해보았습니다!

**Comment by jeuxdeau** [comment]
すごい! ★ʕ•ᴥ•ʔ☆
1. 유효하지 않은 주소는 전부 signin으로 리다이렉트 되는데 의도한 것인가요?
2. Route랑 PrivateRoute 순서 사이에 상관 있나봐
```
<Route exact path="/signin/" component={Signin} />
<PrivateRoute path="/" component={List} />
<Route exact path="/signup/" component={SignUp} />
```
이렇게 하면 signup으로 갔을 대 그냥 singin으로 넘어가 버리고
```
<Route exact path="/signin/" component={Signin} />
<Route exact path="/signup/" component={SignUp} />
<PrivateRoute path="/" component={List} />
```
이렇게 해야 signup으로 잘 들어가진다

**Comment by jeuxdeau** [comment]
윗글 쓰는 사이에 저거 올라와서 충격 받음...........................

**Comment by jinwoo71** [comment]
@SonSang 너무 좋아 ㅋㅋㅋㅋㅋㅋ

**Comment by jeuxdeau** [comment]
@SonSang 나두 ㅎㅎㅎㅎㅎㅎ

**Comment by jinwoo71** [comment]
@SonSang 나 화요일 지나면 프론트도 참여해볼래!!!!!!

**Comment by jeuxdeau** [comment]
JWT 튜토리얼에 있던 CSS인가? ㅋㅋ
브랜치들 어느 정도 합칠까요?

**Comment by jinwoo71** [comment]
@jeuxdeau 
우빈 나 깃 너무 초보라 설명좀 부탁해도될까
브랜치를 합치자는게 login_backend랑 login_front 두 브랜치 머지한다는거야?
그러면 그 이후에는 머지하면 머지 당한 브랜치는 사라지는건가??
그리고 합치면 내가 다시 처음부터 clone 해서 받아온 다음에 작업해야하는거니

**Comment by SonSang** [comment]
@jeuxdeau 
1. 아니! 유효하지 않으면 그렇게 되는 줄은 몰랐네ㅋ큐ㅠ 일단 유효한 페이지에 갔는데 로그인이 안되있으면 무조건 signin으로 보낸다는 의도였어! 
2. 그건 순서도 상관있는데, exact path 랑 그냥 path가 달라서 그렇기도 해. 그냥 path는 '/'뒤에 뭐가 있던지 간에 '/'가 있으면 거기로 보내버리고, exact path는 전체 스트링이 완전히 일치해야만 보내는 거야! 지적한 경우에서는 signup의 exact path 가 실행되기 전에 그냥 path의 '/'가 먼저 실행돼서 거기로 가버린거지ㅎㅎ

**Comment by SonSang** [comment]
@jeuxdeau @jinwoo71 
헷 디자인 재밌다ㅋㅋ 이거 reactstrap이라고 bootstrap을 react로 임포팅한 거 써서 만든거야ㅋㅋ 엄청 쉬우니까 나중에 다 해봐! https://reactstrap.github.io/

**Comment by jinwoo71** [comment]
@SonSang 디자인 덕에 데모할 때 멋좀 살겠다!!!!!!!!!!

**Comment by jeuxdeau** [comment]
@jinwoo71 지금 마스터, 로그인 프론트, 로그인 백이 있는데, 로그인 작업들이 마무리되는 중인 거 같아서 저 셋을 합치면 어떨까 했어! 예를 들어 마스터랑 백 두 브랜치를 합친다고 하면, 두 브랜치를 하나로 만든다고 생각하면 되는데, 마스터에 백엔드를 끌어와서 합칠 수도 있고 백엔드에 마스터를 끌어와서 합칠 수도 있어 우리 같은 경우는 마스터에 나머지 둘을 데려오게 되겠지? 뭐 클론을 다시 해도 상관 없고 ㅋㅋ 만약 세 개가 마스터로 정상적으로 머지된 경우에는 git pull origin master 하면 되겠지?

**Comment by jeuxdeau** [comment]
@SonSang 
かっこういい!
???
이건 외모 칭찬할 때 쓰는 말 같은데?
멋있다가 뭐야 ㅋㅋ하여튼 멋있다.

**Comment by jinwoo71** [comment]
@jeuxdeau 합치자!! 근데 나 backend testscript 짜면서 문제 있나 보는 중이라 이거만 마무리하고 머지하자
테스트 스크립트 짜는거 너무 귀찮다...ㅜㅠ
